---
- name: setup install docker on oel8
  debug:
    msg:
      - 'This playbook is for setup install docker on oel8 , started at {{ansible_date_time.iso8601}}:'

- name: Preparation tasks for server setup
  block:
 #   - import_tasks: prepare_disk_lvm.yml
    - import_tasks: docker_inst.yml








