---
- name: Ensure OPatch is up to date
  shell: >
    source /home/oracle/setEnv.sh &&
    source /home/oracle/grid_env &&
    $ORACLE_HOME/OPatch/opatch version | grep '{{ opatch_version }}'
  register: opatch_check
  ignore_errors: yes

- name: Debug installation output
  debug:
    msg: "{{ opatch_check.stdout_lines }}"

#- name: Backup existing OPatch directory in grid home
#  shell: |
#    mv {{ grid_home }}/OPatch {{ grid_home }}/OPatch_$(date +%Y%m%d%H%M)
#  args:
#    warn: false
#  register: backup_result

#- name: Display OPatch backup result
#  debug:
#    msg: "OPatch directory moved to {{ backup_result.stdout }}"

#- name: Unzip latest OPatch version in grid home
#  shell: |
#    unzip -o /mnt/nfs_share/oracle/soft/patches/p6880880_190000_Linux-x86-64.zip -d {{ grid_home }}
#  args:
#    warn: false
  
#- name: Ensure the directory exists in grid home
#  file:
#    path: "{{ grid_home }}/OPatch"
#    state: directory
#    owner: oracle
#    group: oinstall
#    mode: "0750"
#    recurse: yes

#- name: Backup existing OPatch directory in dbhome home
#  shell: >
#    source /home/oracle/setEnv.sh &&
#    source /home/oracle/db_env &&
#    mv {{ oracle_home }}/OPatch {{ oracle_home }}/OPatch_$(date +%Y%m%d%H%M)
#  args:
#    warn: false
#  register: backup_result
#
#- name: Display OPatch backup result
#  debug:
#    msg: "OPatch directory moved to {{ backup_result.stdout }}"
#
#- name: Unzip latest OPatch version in dbhome home
#  shell: |
#    unzip -o /mnt/nfs_share/oracle/soft/patches/p6880880_190000_Linux-x86-64.zip -d {{ oracle_home }}
#  args:
#    warn: false
#  
#- name: Ensure the directory exists in dbhome home
#  file:
#    path: "{{ oracle_home }}/OPatch"
#    state: directory
#    owner: oracle
#    group: oinstall
#    mode: "0750"
#    recurse: yes

#- name: Get Current Date
#  shell: "date +%Y-%m-%d"
#  register: current_date
#  changed_when: false
#
#- name: Check OPatch Inventory for grid_home
#  shell: "{{ grid_home }}/OPatch/opatch lsinventory -detail -oh {{ grid_home }}"
#  register: opatch_output
#  become: yes
#  become_user: oracle  
#
#- name: Save OPatch Inventory for grid home Output to File
#  shell: "echo '{{ opatch_output.stdout }}' > /mnt/nfs_share/oracle/logs/opatch_lsinventory_grid_{{ current_date.stdout }}.log"
#
#- name: Check OPatch Inventory for db_home
#  shell: "{{ oracle_home }}/OPatch/opatch lsinventory -detail -oh {{ oracle_home }}"
#  register: opatch_output
#  become: yes
#  become_user: oracle  
#
#- name: Save OPatch Inventory for db home Output to File
#  shell: "echo '{{ opatch_output.stdout }}' > /mnt/nfs_share/oracle/logs/opatch_lsinventory_oracle_{{ current_date.stdout }}.log"

#- name: Unzip Oracle Database software
#  unarchive:
#    src: "{{ patch_extract_dir }}/{{ patch_zip_file }}"
#    dest: "{{ patch_extract_dir }}"
#    remote_src: yes
#    owner: oracle
#    group: oinstall
#  become: yes
#  become_user: oracle

#- name: Run OPatch conflict check on grid home
#  command: >
#    {{ grid_home }}/OPatch/opatch prereq CheckConflictAgainstOHWithDetail -phBaseDir {{ patch_location }}/{{ item }}
#  loop: "{{ patch_ids1 }}"
#  register: conflict_check1
#  changed_when: false
#  become: yes
#  become_user: oracle 
#- name: Display conflict check results
#  debug:
#    msg: "{{ conflict_check1.results | map(attribute='stdout') | list }}"
#- name: Run Opatch conflict check on oracle home
#  command: >
#    {{ oracle_home }}/OPatch/opatch prereq CheckConflictAgainstOHWithDetail -phBaseDir {{ patch_location }}/{{ item }}
#  loop: "{{ patch_ids2 }}"
#  register: conflict_check2
#  changed_when: false
#  become: yes
#  become_user: oracle
#- name: Display conflict check results
#  debug:
#    msg: "{{ conflict_check2.results | map(attribute='stdout') | list }}"

- name: Check available free space in /u01
  shell: df --output=avail -BG /u01 | tail -1 | tr -d 'G'
  register: free_space
  changed_when: false

- name: Validate if at least 20GB is available
  fail:
    msg: "Insufficient disk space on /u01. Required: 20GB, Available: {{ free_space.stdout }}GB"
  when: free_space.stdout | int < 20

- name: Display available free space
  debug:
    msg: "Available free space in /u01: {{ free_space.stdout }}GB"

#- name: Perform OPatch conflict check (Analyze) for grid home
#  shell: >
#    source /home/oracle/setEnv.sh && 
#    source /home/oracle/grid_env &&
#    {{ grid_home }}/OPatch/opatchauto apply {{ patch_location }} -oh {{ grid_home }} -analyze
#  register: analyze_result
#  become: yes
#  become_user: root
#  ignore_errors: yes
#
#- name: Display available free space
#  debug:
#    msg: "{{ analyze_result.stdout }}"

#- name: Perform OPatch Apply patch (Apply) for grid home
#  shell: >
#    source /home/oracle/setEnv.sh && 
#    source /home/oracle/grid_env &&
#    {{ grid_home }}/OPatch/opatchauto apply {{ patch_location }} -oh {{ grid_home }}
#  register: apply_result
#  become: yes
#  become_user: root
#  ignore_errors: yes
#
#- name: Display available free space
#  debug:
#    msg: "{{ apply_result.stdout }}"


#- name: Perform OPatch conflict check (Analyze) for oracle home
#  shell: >
#    source /home/oracle/setEnv.sh && 
#    source /home/oracle/db_env &&
#    {{ oracle_home }}/OPatch/opatchauto apply {{ patch_location }} -oh {{ oracle_home }} -analyze
#  register: analyze_result2
#  become: yes
#  become_user: root
#  ignore_errors: yes

#- name: Display available free space
#  debug:
#    msg: "{{ analyze_result2.stdout }}"

- name: Perform OPatch Apply patch (Apply) for oracle home
  shell: >
    source /home/oracle/setEnv.sh && 
    source /home/oracle/db_env &&
    {{ oracle_home }}/OPatch/opatchauto apply {{ patch_location }} -oh {{ oracle_home }}
  register: apply_result2
  become: yes
  become_user: root
  ignore_errors: yes

- name: Display available free space
  debug:
    msg: "{{ apply_result2.stdout }}"


