## This configuration was generated by terraform-provider-oci

resource oci_mysql_mysql_db_system export_mysql_test {
  access_mode = "UNRESTRICTED"
  admin_password = var.admin_password
  admin_username = var.admin_username
  availability_domain = var.availability_domain--kWcK-PHX-AD-1
  backup_policy {
    #defined_tags = <<Optional value not found in discovery>>
    freeform_tags = {
    }
    is_enabled = "true"
    pitr_policy {
      is_enabled = "true"
    }
    retention_in_days = "7"
    soft_delete       = "ENABLED"
    window_start_time = "10:46"
  }
  compartment_id   = var.compartment_ocid
  configuration_id = "ocid1.mysqlconfiguration.oc1..aaaaaaaa3nxmnfhhxmwczg6wymvx2seey2tmqmdmiifekdf77za4worikhea"
  crash_recovery   = "ENABLED"
  data_storage {
    is_auto_expand_storage_enabled = "false"
    #max_storage_size_in_gbs = <<Optional value not found in discovery>>
  }
  data_storage_size_in_gb = var.db_storage_size
  database_console {
    port   = "8443"
    status = "DISABLED"
  }
  database_management = "DISABLED"
  database_mode       = "READ_WRITE"
  defined_tags = {
    "Lift-Auto-Tags.AnyDay" = "*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,0,*,*,*,*,*,0,*#9AM to 9PM IST"
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bommisetty.venkat.siva.prasad@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-12T08:20:07.988Z"
  }
  deletion_policy {
    automatic_backup_retention = "DELETE"
    final_backup               = "SKIP_FINAL_BACKUP"
    is_delete_protected        = "false"
  }
  #description = <<Optional value not found in discovery>>
  display_name = var.db_system_name
  encrypt_data {
    key_generation_type = "SYSTEM"
    #key_id = <<Optional value not found in discovery>>
  }
  #fault_domain = var.fault_domain--FAULT-DOMAIN-1
  freeform_tags = {
    "Template" = "Development or testing"
  }
  #hostname_label = <<Optional value not found in discovery>>
  #ip_address          = "10.5.1.132"
  is_highly_available = "false"
  maintenance {
    maintenance_schedule_type = "REGULAR"
    version_preference        = "OLDEST"
    version_track_preference  = "FOLLOW"
    window_start_time         = "THURSDAY 12:29"
  }
  mysql_version = "8.4.8"
  nsg_ids = [
  ]
  port   = "3306"
  port_x = "33060"
  read_endpoint {
    exclude_ips = [
    ]
    is_enabled = "false"
    #read_endpoint_hostname_label = <<Optional value not found in discovery>>
    #read_endpoint_ip_address = <<Optional value not found in discovery>>
  }
  secure_connections {
    certificate_generation_type = "SYSTEM"
    #certificate_id = <<Optional value not found in discovery>>
  }
  security_attributes = {
  }
  shape_name = "MySQL.2"
  #shutdown_type = <<Optional value not found in discovery>>
  #source = <<Optional value not found in discovery>>
  state     = "ACTIVE"
  subnet_id = "ocid1.subnet.oc1.phx.aaaaaaaa2kks45jnmzxsxezmkcbcd6hvci4quvpemybzzb25e23mq6rawfea"
}

