- name: Create listener using netca
  become: yes
  become_user: oracle
  shell: |
    export ORACLE_HOME={{ ORACLE_HOME }}
    export PATH={{ ORACLE_HOME }}/bin:$PATH
    {{ ORACLE_HOME }}/bin/netca -silent -responsefile {{ ORACLE_HOME }}/assistants/netca/netca.rsp
  args:
    executable: /bin/bash

- name: add tnsnames.ora entry
  template:
    src: tnsnames.ora.j2
    dest: "{{ ORACLE_HOME }}/network/admin/tnsnames.ora"
    owner: oracle
    group: oinstall
    mode: '0644'

