oracle_home: "/u01/app/oracle/product/19.0.0/dbhome_1"
listener_home: "/u01/app/oracle/product/19.0.0/dbhome_1/network/admin"
primary_db: "o19tc"
standby_db: "o19tcsb"
primary_host: "o19cdb01.scslabs.com"
standby_host: "o19csdb01.scslabs.com"
db_user: "oracle"
listener_port: 1521
sys_pwd: "Nxxxxxxxxxxx12"
oracle_base: /u01/app/oracle
audit_file_dest: "{{ oracle_base }}/admin/{{ oracle_sid }}/adump"
control_files_dir: "/u02/oradata/{{ oracle_sid }}/controlfiles"
db_create_file_dest: "/u02/oradata"
db_recovery_file_dest: "/u02/fra"
oracle_sid: "o19tcsb"  # Change to match your DB SID
oracle_group: "oinstall"
log_archive_dest_2: "*.log_archive_dest_2='SERVICE={{ primary_db }} ASYNC VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME={{ primary_db }}'"
log_file_name_convert: "*.log_file_name_convert='{{ primary_db }}','{{ standby_db }}'"
db_file_name_convert: "*.db_file_name_convert='{{ primary_db }}'','{{ standby_db }}'"
redolog_file_dir: "/u02/oradata/{{ oracle_sid }}/onlinelog"