- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: oracle
    group: oinstall
    mode: '0755'
  loop:
    - "{{ mw_home }}"
    - "{{ agent_base }}"
    - "{{ gc_inst }}"
    - "{{ software_library }}"

- name: Ensure directories are empty for a re-run
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ mw_home }}/*"
    - "{{ agent_base }}/*"
    - "{{ gc_inst }}/*"
