#- name: Change ownership of OEM directory
#  file:
#    path: /mnt/nfs_share/oracle/soft/oem
#    owner: oracle
#    group: oinstall
#    state: directory
#    recurse: yes
#  become: yes
#
#- name: Set executable permissions for OEM installer
#  file:
#    path: "{{ software_dir }}/em13500_linux64.bin"
#    mode: '0755'
#
#- name: Perform silent installation of OEM 13c
#  command: "{{ software_dir }}/em13500_linux64.bin -silent -responseFile /tmp/install.rsp"
#  become_user: oracle

#- name: Run allroot.sh script
#  shell: "sh {{ mw_home }}/allroot.sh"
#  become: yes  # Runs as root
#  register: root_sh_result2
#  become_user: root
#
#- name: Display allroot.sh output
#  debug:
#    msg: "{{ root_sh_result2.stdout }}"

- name: Generate OEM response file
  template:
    src: config.rsp.j2
    dest: /tmp/config.rsp
    owner: oracle
    group: oinstall
    mode: '0644'

- name: Run silent OEM 13c configuration
  shell: "{{ mw_home }}/sysman/install/ConfigureGC.sh -silent -responseFile /tmp/config.rsp"
  become: yes
  become_user: oracle
  register: install_output
  ignore_errors: yes

- name: Display installation output
  debug:
    msg: "{{ install_output.stdout_lines }}"
