## This configuration was generated by terraform-provider-oci

resource oci_psql_db_system export_TEST_DB1 {
  #apply_config = <<Optional value not found in discovery>>
  compartment_id = "ocid1.compartment.oc1..aaaaaaaawa7byegnc6qbvskvvq4rxvy7hqexa7prc4lah2efjgkyay5sopzq"
  config_id      = "ocid1.postgresqldefaultconfiguration.oc1.phx.amaaaaaayn42exyajvroliualxgcip5bptenxdwkeggncodpuz2xv2bh55zq"
  #credentials = <<Optional value not found in discovery>>
  db_version = "16"
  defined_tags = {
    "Lift-Auto-Tags.AnyDay" = "*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,0,*,*,*,*,*,0,*#9AM to 9PM IST"
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bommisetty.venkat.siva.prasad@oracle.com"
    "Oracle-Tags.CreatedOn" = "2026-02-12T15:58:39.053Z"
  }
  #description = <<Optional value not found in discovery>>
  display_name = "TEST_DB1"
  freeform_tags = {
  }
  instance_count              = "1"
  instance_memory_size_in_gbs = "16"
  instance_ocpu_count         = "2"
  #instances_details = <<Optional value not found in discovery>>
  management_policy {
    backup_policy {
      backup_start = "00:00"
      #copy_policy = <<Optional value not found in discovery>>
      #days_of_the_month = <<Optional value not found in discovery>>
      #days_of_the_week = <<Optional value not found in discovery>>
      kind           = "DAILY"
      retention_days = "14"
    }
    maintenance_window_start = "WED 07:00"
  }
  network_details {
    is_reader_endpoint_enabled = "false"
    nsg_ids = [
    ]
    #primary_db_endpoint_private_ip = "10.5.1.222"
    subnet_id                      = "ocid1.subnet.oc1.phx.aaaaaaaa2kks45jnmzxsxezmkcbcd6hvci4quvpemybzzb25e23mq6rawfea"
  }
   credentials {
        #Required
        password_details {
            #Required
            password_type = var.db_system_credentials_password_details_password_type

            #Optional
            password = var.db_system_credentials_password_details_password
            #secret_id = oci_vault_secret.test_secret.id
            #secret_version = var.db_system_credentials_password_details_secret_version
        }
        username = var.db_system_credentials_username
    }
  #patch_operations = <<Optional value not found in discovery>>
  shape = "PostgreSQL.VM.Standard.E5.Flex"
  source {
    #backup_id = <<Optional value not found in discovery>>
    #is_having_restore_config_overrides = <<Optional value not found in discovery>>
    source_type = "NONE"
  }
  storage_details {
    availability_domain   = "kWcK:PHX-AD-1"
    iops                  = "75000"
    is_regionally_durable = "false"
    system_type           = "OCI_OPTIMIZED_STORAGE"
  }
  system_type = "OCI_OPTIMIZED_STORAGE"
}

