- name: Test Connection from Primary to Standby
  shell: |
    source /home/oracle/profile_o19tc.sh
    {{ oracle_home }}/bin/sqlplus -s "sys/{{ sys_pwd }}@{{ standby_db }} as sysdba" <<EOF
    SELECT 'SUCCESS' FROM dual;
    EXIT;
    EOF
  register: primary_to_standby
  failed_when: primary_to_standby.rc > 0

- name: Display Primary to Standby Connection Test Result
  debug:
    msg: "{{ primary_to_standby.stdout_lines }}"

- name: Test Connection from Primary to Primary
  shell: |
    source /home/oracle/profile_o19tc.sh
    {{ oracle_home }}/bin/sqlplus -s "sys/{{ sys_pwd }}@{{ primary_db }} as sysdba" <<EOF
    SELECT 'SUCCESS' FROM dual;
    EXIT;
    EOF
  register: primary_to_primary
  failed_when: primary_to_primary.rc > 0

- name: Display Primary to Primary Connection Test Result
  debug:
    msg: "{{ primary_to_primary.stdout_lines }}"
