---
#- name: Configure Primary Database
#  include_tasks: primary.yml
#  when: inventory_hostname == "o19cdb01"
#
#- name: Configure Standby Database
#  include_tasks: standby.yml
#  when: inventory_hostname == "o19csdb01"
#
#- name: test database connections from primary
#  include_tasks: from_prim_conn_test.yml
#  when: inventory_hostname == "o19cdb01"
#
#- name: test database connections from standby
#  include_tasks: from_stdby_conn_test.yml
#  when: inventory_hostname == "o19csdb01"

#- name: rman duplicate for standby
#  include_tasks: rman_duplicate.yml
#  when: inventory_hostname == "o19csdb01"

#- name: update standby parameters
#  include_tasks: recovery.yml
#  when: inventory_hostname == "o19csdb01"

#- name: do a final recovery
#  include_tasks: final_dg_recovery.yml
#  when: inventory_hostname == "o19csdb01"

- name: dg configuration
  include_tasks: dg_broker_setup.yml
  when: inventory_hostname == "o19csdb01"