- name: Copy RMAN Duplicate Template to Standby
  template:
    src: templates/rman_duplicate.j2
    dest: /tmp/rman_duplicate_script.rman
    owner: oracle
    group: oinstall
    mode: '0644'

- name: Run RMAN Duplicate
  shell: |
    source /home/oracle/profile_o19tcsb.sh
    rman auxiliary sys/{{ sys_pwd }}@{{ standby_db }} <<EOF
    @/tmp/rman_duplicate_script.rman
    EXIT;
    EOF
  register: rman_duplicate
  failed_when: rman_duplicate.rc > 0