- name: Ensure required directories exist
  file:
    path: "{{ oracle_home }}/demo/schema"
    state: directory
    owner: oracle
    group: dba
    mode: '0755'

- name: Copy sample schemas ZIP file
  copy:
    src: /mnt/nfs_share/oracle/soft/v19.2.zip
    dest: /tmp/v19.2.zip
    owner: oracle
    group: dba
    mode: '0644'

- name: Unzip sample schemas
  unarchive:
    src: /tmp/v19.2.zip
    dest: /tmp/
    remote_src: yes
    owner: oracle
    group: dba
    mode: '0755'

- name: Remove existing schema directory
  file:
    path: "{{ oracle_home }}/demo/schema"
    state: absent

- name: Copy extracted schema files to Oracle demo schema directory
  copy:
    src: /tmp/db-sample-schemas-19.2/
    dest: "{{ oracle_home }}/demo/schema/"
    remote_src: yes
    owner: oracle
    group: dba
    mode: '0755'

- name: Cleanup temporary files
  file:
    path: /tmp/db-sample-schemas-19.2
    state: absent

- name: Update schema SQL files with correct directory path
  shell: |
    perl -p -i.bak -e 's#__SUB__CWD__#'$(pwd)'#g' */*.sql */*.dat *
  args:
    chdir: "{{ oracle_home }}/demo/schema"

- name: Run sample schema installation
  shell: >
    source /home/oracle/profile_{{ oracle_sid }}.sh &&
    sqlplus / as sysdba <<EOF
    @mksample Nxxxxxx712 Nxxxxx0712  hr oe pm ix sh bi users temp /home/oracle/ {{ pdb_name }}
    EOF
  args:
    chdir: "{{ oracle_home }}/demo/schema"

