---
- name: Copy Oracle Database Creation Script
  template:
    src: create_oracle_db.sh.j2
    dest: /tmp/create_oracle_db.sh
    owner: oracle
    group: oinstall
    mode: '0755'

- name: Execute Database Creation Script
  shell: . /tmp/create_oracle_db.sh
  become_user: oracle
  register: db_creation_output

- name: Display Output of Database Creation
  debug:
    var: db_creation_output.stdout_lines

