- name: Deploy clone script to Proxmox
  ansible.builtin.template:
    src: clone_vm_cloudinit.sh.j2
    dest: /tmp/clone_vm_cloudinit.sh
    mode: '0755'

- name: Execute clone script
  ansible.builtin.shell: /tmp/clone_vm_cloudinit.sh
  register: vm_output

- name: Show VM details (for workflow)
  debug:
    msg:
      vm_name: "{{ vm_name }}"
      vm_ip: "{{ vm_ip }}"

- name: Wait for SSH to be reachable
  wait_for:
    host: "{{ vm_ip }}"
    port: 22
    timeout: 300
  delegate_to: "{{ inventory_hostname }}"

- name: Disable  Cloudinit Further Run 
  shell: |
    ssh -o StrictHostKeyChecking=no nsunke@{{ vm_ip }} \
    "sudo -S systemctl stop firewalld && sudo -S systemctl disable firewalld && sudo -S touch /etc/cloud/cloud-init.disabled"