---
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Move /etc/krb5.conf to /opt
  command: "mv /etc/krb5.conf /opt/krb5.conf"
  args:
    creates: /etc/krb5.conf
- name: Configure /etc/krb5.conf
  copy:
    dest: /etc/krb5.conf
    content: |
      # To opt out of the system crypto-policies configuration of krb5, remove the
      # symlink at /opt/krb5.conf.d/crypto-policies which will not be recreated.
      includedir /etc/krb5.conf.d/
      [logging]
          default = FILE:/var/log/krb5libs.log
          kdc = FILE:/var/log/krb5kdc.log
          admin_server = FILE:/var/log/kadmind.log
      [libdefaults]
          default_realm = SCSLABS.COM
          dns_lookup_realm = false
          dns_lookup_kdc = true
          ticket_lifetime = 24h
          renew_lifetime = 7d
          forwardable = true
          rdns = false
          pkinit_anchors = FILE:/etc/pki/tls/certs/ca-bundle.crt
          spake_preauth_groups = edwards25519
          default_ccache_name = KEYRING:persistent:%{uid}
          udp_preference_limit = 0
          default_tgs_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 rc4-hmac
          default_tkt_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 rc4-hmac
          permitted_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 rc4-hmac
      [realms]
      [domain_realm]

- name: Discover and join the domain
  command: "echo 'kinit administrator@SCSLABS.COM'"
  command: "klist"
  command: "echo 'realm join --user={{ domain_user }} {{ domain_name }}'"
  register: realm_result
  changed_when: "'already joined' not in realm_result.stdout"
  ignore_errors: yes

- name: Configure SSSD to allow login without domain suffix
  lineinfile:
    path: /etc/sssd/sssd.conf
    regexp: '^use_fully_qualified_names'
    line: 'use_fully_qualified_names = False'
  notify: Restart SSSD

- name: Enable automatic home directory creation
  command: "authconfig --enablemkhomedir --update"
  changed_when: false

