[all]
pve.scslabs.dpdns.org ansible_host=192.168.1.10 ansible_user=root
#o9o26aiasm01.scslabs.dpdns.org ansible_host=192.168.1.15 ansible_user=nsunke
#o9o26aiasm02.scslabs.dpdns.org ansible_host=192.168.1.16 ansible_user=nsunke
o9o26airac01 ansible_host=192.168.1.17 ansible_user=nsunke
o9o26airac02 ansible_host=192.168.1.18 ansible_user=nsunke
awx.scslabs.dpdns.org ansible_host=192.168.1.13 ansible_user=nsunke

[test]
#vmprvtst  ansible_host=192.168.1.14 ansible_user=nsunke

[proxmox]
pve.scslabs.dpdns.org ansible_host=192.168.1.10 ansible_user=root

[dbserver]
#o9o26aidb01 ansible_host=192.168.1.14 ansible_user=nsunke
o9o26aiasm01 ansible_host=192.168.1.15 ansible_user=nsunke
#o9o26aiasm02.scslabs.dpdns.org ansible_host=192.168.1.16 ansible_user=nsunke

[racnodes]
o9o26airac01 ansible_host=192.168.1.17 ansible_user=nsunke
o9o26airac02 ansible_host=192.168.1.18 ansible_user=nsunke

[awx]
awx.scslabs.dpdns.org ansible_host=192.168.1.13 ansible_user=nsunke