# ------------------------------------------------------------------
# 1️⃣ Execute Grid Configuration Tools
# ------------------------------------------------------------------

- name: Execute Grid Configuration Tools
  become: yes
  become_user: grid
  shell: >
    {{ grid_home }}/gridSetup.sh -silent -executeConfigTools
    -responseFile {{ grid_home }}/install/response/gridsetup.rsp
    INVENTORY_LOCATION={{ ora_inventory }}
    SELECTED_LANGUAGES={{ ora_languages }}
    oracle.install.option=CRS_CONFIG
    ORACLE_BASE={{ grid_base }}
    oracle.install.asm.OSDBA=dba
    oracle.install.asm.OSASM=dba
    oracle.install.crs.config.scanType=LOCAL_SCAN
    oracle.install.crs.config.gpnp.scanName={{ scan_name }}
    oracle.install.crs.config.gpnp.scanPort={{ scan_port }}
    oracle.install.crs.config.ClusterConfiguration=STANDALONE
    oracle.install.crs.config.configureAsExtendedCluster=false
    oracle.install.crs.config.clusterName={{ cluster_name }}
    oracle.install.crs.config.gpnp.configureGNS=false
    oracle.install.crs.config.autoConfigureClusterNodeVIP=false
    oracle.install.crs.config.clusterNodes={{ node1_fq }}:{{ node1_vip }}:HUB,{{ node2_fq }}:{{ node2_vip }}:HUB
    oracle.install.crs.config.networkInterfaceList={{ public_if }}:{{ public_subnet }}:1,{{ private_if }}:{{ private_subnet }}:5
    oracle.install.crs.configureGIMR=false
    oracle.install.crs.config.storageOption=FLEX_ASM_STORAGE
    oracle.install.crs.config.useIPMI=false
    oracle.install.asm.storageOption=ASM
    oracle.install.asm.diskGroup.name=CRS
    oracle.install.asm.diskGroup.redundancy=EXTERNAL
    oracle.install.asm.diskGroup.disksWithFailureGroupNames=/dev/asm-crs,CRSFG1
    oracle.install.asm.diskGroup.disks=/dev/asm-crs
    oracle.install.asm.diskGroup.diskDiscoveryString=/dev/asm-*
    oracle.install.asm.monitorPassword={{ sys_password }}
    oracle.install.asm.SYSASMPassword={{ sys_password }}
    oracle.install.asm.configureAFD=false
    oracle.install.crs.configureRHPS=false
    oracle.install.crs.config.ignoreDownNodes=false
    oracle.install.config.managementOption=NONE
    oracle.install.config.omsPort=0
    oracle.install.crs.rootconfig.executeRootScript=false
  register: grid_config
  async: 3600
  poll: 20

- name: Save Grid Configuration Log
  copy:
    content: "{{ grid_config.stdout }}"
    dest: /tmp/grid_execute_config.log



