# ------------------------------------------------
# Proxmox Bridges
# ------------------------------------------------
public_bridge: vmbr0
private_bridge: vmbr1
san_bridge: vmbr2

# ------------------------------------------------
# VM Definitions
# ------------------------------------------------
vms:
  - vmid: 111
  - vmid: 112
