---
- name: setup oracle linux server for Oracle 19c DB installation
  debug:
    msg:
      - 'This playbook is for setup oracle linux server for Oracle 19c   DB installation , started at {{ansible_date_time.iso8601}}:'

- name: Preparation tasks for server setup
  block:
    - import_tasks: prepare_disk_lvm.yml
    - import_tasks: install_os_packages.yml
    - import_tasks: oracle_pwd_set.yml
    - import_tasks: oracle_user_environment_setup.yml
    - import_tasks: mount_nfs.yml
    - import_tasks: oracle_file.yml
    - import_tasks: install_oracle.yml
    - import_tasks: ora_root.yml

