---
- name: Create oracle home directory
  file:
    path: "{{ ORACLE_HOME }}"
    state: directory
    owner: oracle
    group: oinstall
    mode: '0755'
#- name: Copy a file and unzip on the remote server
#  copy:
#    src: "/u01/soft/LINUX.X64_193000_db_home.zip"  # Path to the file on the Ansible control host
#    dest: "{{ ORACLE_HOME }}/LINUX.X64_193000_db_home.zip"  # Path on the remote server where the file will be copied

- name: Unzip Oracle database installation files
  become: yes
  become_user: oracle
  unarchive:
    src: "/mnt/nfsshare/oracle/soft/LINUX.X64_193000_db_home.zip"
    dest: "{{ ORACLE_HOME }}"
    remote_src: yes



- name: ownership of  oracle home directory
  file:
    path: "{{ ORACLE_HOME }}"
    owner: oracle
    group: oinstall

