---
- name: Install LVM2 package
  ansible.builtin.yum:
    name: lvm2
    state: present

- name: Create physical volumes
  ansible.builtin.command: "pvcreate {{ item.device }}"
  loop: "{{ pv_disks }}"
  register: pv_creation
  ignore_errors: yes  # Ignore errors if PV already exists

- name: Create volume groups
  ansible.builtin.command: "vgcreate {{ item.vg_name }} {{ item.device }}"
  loop: "{{ pv_disks }}"
  register: vg_creation

- name: Create logical volumes
  ansible.builtin.command: "lvcreate -l 100%FREE -n {{ item.lv_name }} {{ item.vg_name }}"
  loop: "{{ pv_disks }}"
  register: lv_creation

- name: Create XFS filesystem on logical volumes
  ansible.builtin.command: "mkfs.xfs /dev/{{ item.vg_name }}/{{ item.lv_name }}"
  loop: "{{ pv_disks }}"
  register: xfs_creation

- name: Create mount points
  ansible.builtin.file:
    path: "{{ item.mount_point }}"
    state: directory
  loop: "{{ pv_disks }}"

- name: Ensure /etc/fstab entries for the logical volumes
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/dev/{{ item.vg_name }}/{{ item.lv_name }} {{ item.mount_point }} xfs defaults 0 0"
    state: present
  loop: "{{ pv_disks }}"

- name: Mount the logical volumes
  ansible.builtin.mount:
    path: "{{ item.mount_point }}"
    src: "/dev/{{ item.vg_name }}/{{ item.lv_name }}"
    fstype: xfs
    state: mounted
  loop: "{{ pv_disks }}"
  